// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMKDPbtyHxa7Gnsdte-KyFgedYcvBGFJY',
    appId: '1:122267568289:web:dbe10e92c2e01b2fee48e0',
    messagingSenderId: '122267568289',
    projectId: 'store-molino-diamante',
    authDomain: 'store-molino-diamante.firebaseapp.com',
    storageBucket: 'store-molino-diamante.appspot.com',
    measurementId: 'G-N2NRQBG4ER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuG-uLoE4QIKNKpLJlJdch-kjSJ-8kST4',
    appId: '1:122267568289:android:748ad750dd0b28f5ee48e0',
    messagingSenderId: '122267568289',
    projectId: 'store-molino-diamante',
    storageBucket: 'store-molino-diamante.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkzQ9GdWfkyfxyixEn4hYgfmLm_8Qc4l0',
    appId: '1:122267568289:ios:67c84b41b87a3fb1ee48e0',
    messagingSenderId: '122267568289',
    projectId: 'store-molino-diamante',
    storageBucket: 'store-molino-diamante.appspot.com',
    iosBundleId: 'com.example.storeMolinoDiamante',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkzQ9GdWfkyfxyixEn4hYgfmLm_8Qc4l0',
    appId: '1:122267568289:ios:67c84b41b87a3fb1ee48e0',
    messagingSenderId: '122267568289',
    projectId: 'store-molino-diamante',
    storageBucket: 'store-molino-diamante.appspot.com',
    iosBundleId: 'com.example.storeMolinoDiamante',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMKDPbtyHxa7Gnsdte-KyFgedYcvBGFJY',
    appId: '1:122267568289:web:6e3159bd6a6f69f4ee48e0',
    messagingSenderId: '122267568289',
    projectId: 'store-molino-diamante',
    authDomain: 'store-molino-diamante.firebaseapp.com',
    storageBucket: 'store-molino-diamante.appspot.com',
    measurementId: 'G-E739JFPJDT',
  );
}
